#!/usr/bin/env python2
import subprocess,re,json,logging

p = subprocess.Popen(["sudo smartctl --scan-open|awk -F '#' '{print $1}'|sed '/^[[:space:]]*$/d'"],shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
out = {"data": []}
for line in p.stdout:
  out["data"].append({ "{#DISKCMD}": str(line.rstrip())})
  p.stdout.flush()
print(json.dumps(out, indent=4, sort_keys=True))

