#!/usr/bin/env bash

echo "#### Memory"
(IFS=": "; sudo dmidecode -qt 17|\
while read k v; do
    if [ "$k" != "" ]; then
        eval ${k//[[:space:]]/}=\"$v\"
    else
        echo "$Size"
    fi
done)\
| sort | uniq -c | sed -E "s/\s+([0-9]+)\s+(.+)/\1 x \2/"
~                                                         
